### ISSUE TITLE
Color code is different.

### ISSUE THREAD

**Issue by jay94ks** [gavinlyonsrepo/ST7735_TFT_PICO#2]
Current definition:
```
#define ST7735_BLACK 0x0000
#define ST7735_WHITE 0xFFFF
```

but, this must be:
```
#define ST7735_BLACK 0xFFFF
#define ST7735_WHITE 0x0000
```

for my TFT display.

![working example](https://github.com/gavinlyonsrepo/ST7735_TFT_PICO/assets/33371449/58dfd585-0f63-4153-a710-292bb1e1e25b)

this full code and schematic can be found in my repository: [my repository](https://github.com/jay94ks/simple-np).

Currently, I defined them to alias.
![alias](https://github.com/gavinlyonsrepo/ST7735_TFT_PICO/assets/33371449/b85c2c48-7147-4620-a013-2b245c1b01c7)

**Comment by gavinlyonsrepo** [comment]
Hello 

What about other colors ?
Inverted colors but a working display is a sign of incorrect 'PCB_TYPE' picked. Method TFTInitPCBType()
Did you they all 4 PCB_types?

See readme user options 3
https://github.com/gavinlyonsrepo/ST7735_TFT_PICO?tab=readme-ov-file#user-options

https://gavinlyonsrepo.github.io/misc/software_docs/ST7735_TFT_PICO/classST7735__TFT.html#aef0a516d5fffd1d8ceaeb47175d68893

regards

**Comment by jay94ks** [comment]
> Hello
> 
> What about other colors ? Inverted colors but a working display is a sign of incorrect 'PCB_TYPE' picked. Method TFTInitPCBType() Did you try all 4 PCB_types?
> 
> See readme user options 3 https://github.com/gavinlyonsrepo/ST7735_TFT_PICO?tab=readme-ov-file#user-options
> 
> https://gavinlyonsrepo.github.io/misc/software_docs/ST7735_TFT_PICO/classST7735__TFT.html#aef0a516d5fffd1d8ceaeb47175d68893
> 
> regards

Okay I'll try again. and I'll share its result you.

Thanks.

**Comment by jay94ks** [comment]
@gavinlyonsrepo Hello, This pictures describe color code different test.
First picture of this issue I uploaded was initialized by:
```
_tft.TFTInitPCBType(ST7735_TFT::TFT_ST7735S_Black);
```

And additional tests are:

### 1
![KakaoTalk_20240324_163849206](https://github.com/gavinlyonsrepo/ST7735_TFT_PICO/assets/33371449/0bdd4a43-69e0-4bb2-8a3b-b947bb866f3d)
![KakaoTalk_20240324_163849206_01](https://github.com/gavinlyonsrepo/ST7735_TFT_PICO/assets/33371449/3dad857a-1596-49dc-8912-873c545a8c38)

### 2
![KakaoTalk_20240324_163849206_02](https://github.com/gavinlyonsrepo/ST7735_TFT_PICO/assets/33371449/18c54079-5451-4e24-9a90-0b0a6eba97e6)
![KakaoTalk_20240324_163849206_03](https://github.com/gavinlyonsrepo/ST7735_TFT_PICO/assets/33371449/a61ea449-81ae-4b8d-9e65-b765300164ae)

### 3
![KakaoTalk_20240324_163849206_04](https://github.com/gavinlyonsrepo/ST7735_TFT_PICO/assets/33371449/c02ed6ca-3da8-4037-800d-c3fa0bee95b5)
![KakaoTalk_20240324_163849206_05](https://github.com/gavinlyonsrepo/ST7735_TFT_PICO/assets/33371449/db268de9-da88-43db-ae77-46196306d8dd)

**Comment by jay94ks** [comment]
> Hi
> 
> Regarding suggestion. There are 65,536 colours so its not just a matter of switching black and white. Initial routines need to be written and it may have implications for rotate and change mode methods as well. The display would have be initialized with correct RGB Gamma Correction Setting's for its controller. The ali-express listing says its a IC-ST7735S in which case 'TFT_ST7735S_Black' should have worked.
> 
> I don't know whats wrong here. Would need more information on what controller variant this is and a datasheet in order to make changes.

Okay, I bought more TFT displays from there, If you let me know your postbox address, I can send one through delivery service. but, I live in South Korea,  it may take 1 week to 2 weeks.
