### ISSUE TITLE
How to add this to arduino IDE?

### ISSUE THREAD

**Issue by ProgramistaZaDyszke** [gavinlyonsrepo/ST7735_TFT_PICO#3]
Error: 13 INTERNAL: Library install failed: moving extracted archive to destination dir: library not valid

**Comment by gavinlyonsrepo** [comment]
Hi 

I don't know , I never used the arduino IDE for RPI PICO projects. 
The tool chain i used as per readme is 

* Developed on Tool chain:
	1. Raspberry pi PICO RP2040
	2. SDK(1.4.0) C++
	3. compiler G++ for arm-none-eabi((15:10.3-2021.07-4) 
	4. CMAKE(VERSION 3.12) , VScode IDE (1.84.2)
	5. Linux Mint 21.2
